task ready
js-tasks-ru/jsbasic-20240520_xolab pull request #1
Opened 2024-05-20 18:26 UTC by xolab

2024-05-20 18:26 UTC, jsru-1 commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2024-05-20 21:07 UTC, SinimaWath requested changes

2024-05-20 21:07 UTC, SinimaWath commented on 0-module/1-task/index.js
> +sum(2, 2);
В файле с задачей должна быть только задача. Убери вызов `sum`, пожалуйста ;)

2024-05-21 09:26 UTC, xolab commented on 0-module/1-task/index.js
> +sum(2, 2);
готово

2024-05-22 14:25 UTC, SinimaWath approved these changes
Все круто!

2024-05-22 14:25 UTC, merged